# Generated by Django 5.1 on 2024-08-15 12:04

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="EventParticipant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idnumber",
                    models.CharField(
                        max_length=260,
                        verbose_name="Уникальный строковый идентификатор",
                    ),
                ),
                (
                    "datecreated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "datemodified",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения записи"
                    ),
                ),
                (
                    "dateaccessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата доступа к записи"
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("student", "Студент"),
                            ("teacher", "Преподаватель"),
                            ("assistant", "Ассистент"),
                        ],
                        max_length=48,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Участник события",
                "verbose_name_plural": "Участники события",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idnumber",
                    models.CharField(
                        max_length=260,
                        verbose_name="Уникальный строковый идентификатор",
                    ),
                ),
                (
                    "datecreated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "datemodified",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения записи"
                    ),
                ),
                (
                    "dateaccessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата доступа к записи"
                    ),
                ),
                (
                    "kind",
                    models.CharField(
                        choices=[
                            ("LEC", "Лекционное занятие"),
                            ("LAB", "Лабораторная работа"),
                            ("PRA", "Практическое занятие"),
                            ("MAN", "На производстве"),
                        ],
                        max_length=3,
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("participants", models.ManyToManyField(to="api.eventparticipant")),
            ],
            options={
                "verbose_name": "Событие",
                "verbose_name_plural": "События",
            },
        ),
        migrations.CreateModel(
            name="EventPlace",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idnumber",
                    models.CharField(
                        max_length=260,
                        verbose_name="Уникальный строковый идентификатор",
                    ),
                ),
                (
                    "datecreated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "datemodified",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения записи"
                    ),
                ),
                (
                    "dateaccessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата доступа к записи"
                    ),
                ),
                ("building", models.CharField(max_length=128)),
                ("room", models.CharField(max_length=64)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Место проведения события",
                "verbose_name_plural": "Места проведения события",
            },
        ),
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idnumber",
                    models.CharField(
                        max_length=260,
                        verbose_name="Уникальный строковый идентификатор",
                    ),
                ),
                (
                    "datecreated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "datemodified",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения записи"
                    ),
                ),
                (
                    "dateaccessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата доступа к записи"
                    ),
                ),
                ("faculty", models.CharField(max_length=32)),
                (
                    "scope",
                    models.CharField(
                        choices=[
                            ("BACHELOR", "Бакалавриат"),
                            ("MASTER", "Магистрант"),
                            ("POSTGRADUATE", "Аспирантура"),
                            ("CONSULTATION", "Консультация"),
                        ],
                        max_length=32,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=128, verbose_name="Название расписания"
                    ),
                ),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                ("events", models.ManyToManyField(to="api.event")),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Subject",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idnumber",
                    models.CharField(
                        max_length=260,
                        verbose_name="Уникальный строковый идентификатор",
                    ),
                ),
                (
                    "datecreated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "datemodified",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения записи"
                    ),
                ),
                (
                    "dateaccessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата доступа к записи"
                    ),
                ),
                ("name", models.CharField(max_length=256)),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Предмет",
                "verbose_name_plural": "Предметы",
            },
        ),
        migrations.AddField(
            model_name="event",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="api.subject"
            ),
        ),
        migrations.CreateModel(
            name="TimeSlot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idnumber",
                    models.CharField(
                        max_length=260,
                        verbose_name="Уникальный строковый идентификатор",
                    ),
                ),
                (
                    "datecreated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "datemodified",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения записи"
                    ),
                ),
                (
                    "dateaccessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата доступа к записи"
                    ),
                ),
                ("start_time", models.TimeField(verbose_name="Время начала")),
                ("end_time", models.TimeField(verbose_name="Время окончания")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Время проведения события",
                "verbose_name_plural": "Времена проведения события",
            },
        ),
        migrations.CreateModel(
            name="EventHolding",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idnumber",
                    models.CharField(
                        max_length=260,
                        verbose_name="Уникальный строковый идентификатор",
                    ),
                ),
                (
                    "datecreated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "datemodified",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения записи"
                    ),
                ),
                (
                    "dateaccessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата доступа к записи"
                    ),
                ),
                ("date", models.DateField()),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "event",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.event",
                    ),
                ),
                (
                    "place",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.eventplace",
                    ),
                ),
                (
                    "slot",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="api.timeslot",
                    ),
                ),
            ],
            options={
                "verbose_name": "Информация о проведении события",
                "verbose_name_plural": "Информация о проведении события",
            },
        ),
    ]
