# Generated by Django 5.1 on 2024-08-28 19:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EventKind',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=260, null=True, unique=True, verbose_name='Уникальный строковый идентификатор')),
                ('datecreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('datemodified', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения записи')),
                ('dateaccessed', models.DateTimeField(blank=True, null=True, verbose_name='Дата доступа к записи')),
                ('note', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Комментарий для этой записи')),
                ('name', models.CharField(max_length=64, verbose_name='Название типа')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Тип события',
                'verbose_name_plural': 'Типы событий',
            },
        ),
        migrations.CreateModel(
            name='EventParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=260, null=True, unique=True, verbose_name='Уникальный строковый идентификатор')),
                ('datecreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('datemodified', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения записи')),
                ('dateaccessed', models.DateTimeField(blank=True, null=True, verbose_name='Дата доступа к записи')),
                ('note', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Комментарий для этой записи')),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                ('role', models.CharField(choices=[('student', 'Студент'), ('teacher', 'Преподаватель'), ('assistant', 'Ассистент')], max_length=48, verbose_name='Роль')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Участник события',
                'verbose_name_plural': 'Участники события',
            },
        ),
        migrations.CreateModel(
            name='EventPlace',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=260, null=True, unique=True, verbose_name='Уникальный строковый идентификатор')),
                ('datecreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('datemodified', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения записи')),
                ('dateaccessed', models.DateTimeField(blank=True, null=True, verbose_name='Дата доступа к записи')),
                ('note', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Комментарий для этой записи')),
                ('building', models.CharField(max_length=128, verbose_name='Корпус')),
                ('room', models.CharField(max_length=64, verbose_name='Аудитория')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Место проведения события',
                'verbose_name_plural': 'Места проведения события',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=260, null=True, unique=True, verbose_name='Уникальный строковый идентификатор')),
                ('datecreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('datemodified', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения записи')),
                ('dateaccessed', models.DateTimeField(blank=True, null=True, verbose_name='Дата доступа к записи')),
                ('note', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Комментарий для этой записи')),
                ('faculty', models.CharField(max_length=32, verbose_name='Факультет')),
                ('scope', models.CharField(choices=[('bachelor', 'Бакалавриат'), ('master', 'Магистратура'), ('postgraduate', 'Аспирантура'), ('consultation', 'Консультация')], max_length=32, verbose_name='Обучение')),
                ('course', models.IntegerField(verbose_name='Курс')),
                ('semester', models.IntegerField(verbose_name='Семестр')),
                ('years', models.CharField(max_length=16, verbose_name='Учебный год')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписания',
            },
        ),
        migrations.CreateModel(
            name='Subject',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=260, null=True, unique=True, verbose_name='Уникальный строковый идентификатор')),
                ('datecreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('datemodified', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения записи')),
                ('dateaccessed', models.DateTimeField(blank=True, null=True, verbose_name='Дата доступа к записи')),
                ('note', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Комментарий для этой записи')),
                ('name', models.CharField(max_length=256, verbose_name='Название')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Предмет',
                'verbose_name_plural': 'Предметы',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=260, null=True, unique=True, verbose_name='Уникальный строковый идентификатор')),
                ('datecreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('datemodified', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения записи')),
                ('dateaccessed', models.DateTimeField(blank=True, null=True, verbose_name='Дата доступа к записи')),
                ('note', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Комментарий для этой записи')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('kind', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.eventkind', verbose_name='Тип')),
                ('participants', models.ManyToManyField(to='api.eventparticipant', verbose_name='Участники')),
                ('schedule', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.schedule', verbose_name='Связанное расписание')),
                ('subject', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.subject', verbose_name='Предмет')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
        migrations.CreateModel(
            name='TimeSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=260, null=True, unique=True, verbose_name='Уникальный строковый идентификатор')),
                ('datecreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('datemodified', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения записи')),
                ('dateaccessed', models.DateTimeField(blank=True, null=True, verbose_name='Дата доступа к записи')),
                ('note', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Комментарий для этой записи')),
                ('start_time', models.TimeField(verbose_name='Время начала')),
                ('end_time', models.TimeField(null=True, verbose_name='Время окончания')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
            ],
            options={
                'verbose_name': 'Время проведения события',
                'verbose_name_plural': 'Времена проведения события',
            },
        ),
        migrations.CreateModel(
            name='EventHolding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idnumber', models.CharField(max_length=260, null=True, unique=True, verbose_name='Уникальный строковый идентификатор')),
                ('datecreated', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания записи')),
                ('datemodified', models.DateTimeField(auto_now_add=True, verbose_name='Дата изменения записи')),
                ('dateaccessed', models.DateTimeField(blank=True, null=True, verbose_name='Дата доступа к записи')),
                ('note', models.TextField(blank=True, max_length=1024, null=True, verbose_name='Комментарий для этой записи')),
                ('date', models.DateField(verbose_name='Дата')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Автор записи')),
                ('event', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='holdings', to='api.event', verbose_name='Связанное событие')),
                ('place', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.eventplace', verbose_name='Место')),
                ('time_slot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='api.timeslot', verbose_name='Временной интервал')),
            ],
            options={
                'verbose_name': 'Информация о проведении события',
                'verbose_name_plural': 'Информация о проведении события',
            },
        ),
    ]
