# Generated by Django 5.1 on 2024-09-03 09:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="idnumber",
            field=models.CharField(
                blank=True,
                max_length=260,
                null=True,
                unique=True,
                verbose_name="Уникальный строковый идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="eventholding",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="eventholding",
            name="idnumber",
            field=models.CharField(
                blank=True,
                max_length=260,
                null=True,
                unique=True,
                verbose_name="Уникальный строковый идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="eventkind",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="eventkind",
            name="idnumber",
            field=models.CharField(
                blank=True,
                max_length=260,
                null=True,
                unique=True,
                verbose_name="Уникальный строковый идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="eventparticipant",
            name="idnumber",
            field=models.CharField(
                blank=True,
                max_length=260,
                null=True,
                unique=True,
                verbose_name="Уникальный строковый идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="eventplace",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="eventplace",
            name="idnumber",
            field=models.CharField(
                blank=True,
                max_length=260,
                null=True,
                unique=True,
                verbose_name="Уникальный строковый идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="idnumber",
            field=models.CharField(
                blank=True,
                max_length=260,
                null=True,
                unique=True,
                verbose_name="Уникальный строковый идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="subject",
            name="idnumber",
            field=models.CharField(
                blank=True,
                max_length=260,
                null=True,
                unique=True,
                verbose_name="Уникальный строковый идентификатор",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="author",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
                verbose_name="Автор записи",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="idnumber",
            field=models.CharField(
                blank=True,
                max_length=260,
                null=True,
                unique=True,
                verbose_name="Уникальный строковый идентификатор",
            ),
        ),
    ]
