# Generated by Django 5.1 on 2024-08-16 13:10

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="schedule",
            options={"verbose_name": "Расписание", "verbose_name_plural": "Расписания"},
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="name",
        ),
        migrations.AddField(
            model_name="event",
            name="note",
            field=models.TextField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Комментарий для этой записи",
            ),
        ),
        migrations.AddField(
            model_name="eventholding",
            name="note",
            field=models.TextField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Комментарий для этой записи",
            ),
        ),
        migrations.AddField(
            model_name="eventparticipant",
            name="note",
            field=models.TextField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Комментарий для этой записи",
            ),
        ),
        migrations.AddField(
            model_name="eventplace",
            name="note",
            field=models.TextField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Комментарий для этой записи",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="course",
            field=models.IntegerField(default=1, verbose_name="Курс"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="course_finish",
            field=models.DateField(
                default=datetime.datetime(2024, 1, 1, 0, 0),
                verbose_name="Окончание учебного года",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="course_start",
            field=models.DateField(
                default=datetime.datetime(2024, 1, 1, 0, 0),
                verbose_name="Начало учебного года",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="schedule",
            name="note",
            field=models.TextField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Комментарий для этой записи",
            ),
        ),
        migrations.AddField(
            model_name="schedule",
            name="semester",
            field=models.IntegerField(default=1, verbose_name="Семестр"),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="subject",
            name="note",
            field=models.TextField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Комментарий для этой записи",
            ),
        ),
        migrations.AddField(
            model_name="timeslot",
            name="note",
            field=models.TextField(
                blank=True,
                max_length=1024,
                null=True,
                verbose_name="Комментарий для этой записи",
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="subject",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.subject"
            ),
        ),
        migrations.AlterField(
            model_name="eventholding",
            name="place",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.eventplace",
            ),
        ),
        migrations.AlterField(
            model_name="eventholding",
            name="slot",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="api.timeslot",
            ),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="events",
            field=models.ManyToManyField(to="api.event", verbose_name="Занятия"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="faculty",
            field=models.CharField(max_length=32, verbose_name="Факультет"),
        ),
        migrations.AlterField(
            model_name="schedule",
            name="scope",
            field=models.CharField(
                choices=[
                    ("bachelor", "Бакалавриат"),
                    ("master", "Магистратура"),
                    ("postgraduate", "Аспирантура"),
                    ("consultation", "Консультация"),
                ],
                max_length=32,
                verbose_name="Обучение",
            ),
        ),
        migrations.AlterField(
            model_name="timeslot",
            name="end_time",
            field=models.TimeField(null=True, verbose_name="Время окончания"),
        ),
        migrations.CreateModel(
            name="EventKind",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "idnumber",
                    models.CharField(
                        max_length=260,
                        verbose_name="Уникальный строковый идентификатор",
                    ),
                ),
                (
                    "datecreated",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания записи"
                    ),
                ),
                (
                    "datemodified",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата изменения записи"
                    ),
                ),
                (
                    "dateaccessed",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="Дата доступа к записи"
                    ),
                ),
                (
                    "note",
                    models.TextField(
                        blank=True,
                        max_length=1024,
                        null=True,
                        verbose_name="Комментарий для этой записи",
                    ),
                ),
                ("name", models.CharField(max_length=64, verbose_name="Название типа")),
                (
                    "author",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Тип события",
                "verbose_name_plural": "Типы событий",
            },
        ),
        migrations.AlterField(
            model_name="event",
            name="kind",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="api.eventkind"
            ),
        ),
    ]
