# Generated by Django 5.1 on 2024-08-17 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("api", "0002_alter_schedule_options_remove_schedule_name_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="schedule",
            name="course_finish",
        ),
        migrations.RemoveField(
            model_name="schedule",
            name="course_start",
        ),
        migrations.AddField(
            model_name="schedule",
            name="years",
            field=models.CharField(
                default="2024-2025", max_length=16, verbose_name="Учебный год"
            ),
            preserve_default=False,
        ),
    ]
