# Generated by Django 5.2.dev20241016095222 on 2025-02-12 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_remove_event_kind_remove_event_participants_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='department',
            name='parent_department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.department', verbose_name='Родительское подразделение'),
        ),
    ]
