# Generated by Django 5.2.dev20241016095222 on 2025-02-21 09:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_daydateoverride_schedule_day_override'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='schedule',
            name='day_override',
        ),
        migrations.AddField(
            model_name='daydateoverride',
            name='schedule',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='overrides', to='api.schedule', verbose_name='Расписание'),
        ),
    ]
