# Generated by Django 5.2.dev20241016095222 on 2025-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_remove_schedule_day_override_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='daydateoverride',
            name='organization',
        ),
        migrations.AlterField(
            model_name='daydateoverride',
            name='day_destination',
            field=models.DateField(verbose_name='Перенести на дату'),
        ),
        migrations.AlterField(
            model_name='daydateoverride',
            name='day_source',
            field=models.DateField(verbose_name='Перенести с даты'),
        ),
        migrations.RemoveField(
            model_name='daydateoverride',
            name='schedule',
        ),
        migrations.AddField(
            model_name='daydateoverride',
            name='schedule',
            field=models.ManyToManyField(null=True, related_name='day_overrides', to='api.schedule', verbose_name='Расписание'),
        ),
    ]
