# Generated by Django 5.2.dev20241016095222 on 2025-02-21 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_remove_daydateoverride_organization_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='daydateoverride',
            name='schedule',
            field=models.ManyToManyField(related_name='day_overrides', to='api.schedule', verbose_name='Расписание'),
        ),
    ]
